/**
 * APEX v13 — Méta-marketplace catalog (30+ providers).
 * Auto-split from services/apex-meta-marketplace.ts (refactor 2026-05-08).
 *
 * HONNÊTETÉ :
 *  - pwa_compatible=true → fetch direct browser OK (CORS allow + tier gratuit).
 *  - pwa_compatible=false → besoin Cloudflare Worker proxy OR OAuth dance.
 *  - Tous les `api_endpoint` sont vérifiés contre la doc officielle (mai 2026).
 */

import type { MarketplaceProvider } from '../core-svc/apex-meta-marketplace-types.js';

export const META_MARKETPLACE_CATALOG: readonly MarketplaceProvider[] = [
  /* ----- A. IA / ML ----- */
  {
    id: 'huggingface',
    name: 'HuggingFace Hub',
    category: 'ai-ml',
    url: 'https://huggingface.co',
    api_endpoint: 'https://huggingface.co/api/models',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    rate_limit: 'soft (no auth)',
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Modèles, datasets et spaces IA — open-source, search libre.',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    category: 'ai-ml',
    url: 'https://replicate.com',
    api_endpoint: 'https://api.replicate.com/v1/models',
    api_key_required: true,
    api_key_service: 'ax_replicate_token',
    search_method: 'api-key',
    free_tier_available: true,
    rate_limit: '600/min',
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Modèles IA hébergés (image, audio, vidéo, LLM) facturés à l\'inférence.',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter Models',
    category: 'ai-ml',
    url: 'https://openrouter.ai',
    api_endpoint: 'https://openrouter.ai/api/v1/models',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'LLMs unifiés (Claude, GPT, Gemini, Mistral, Llama) sous une seule API.',
  },
  {
    id: 'ollama',
    name: 'Ollama Models',
    category: 'ai-ml',
    url: 'https://ollama.com/library',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'LLMs locaux téléchargeables (Llama, Mistral, Phi, Gemma…).',
  },
  {
    id: 'civitai',
    name: 'Civitai',
    category: 'ai-ml',
    url: 'https://civitai.com',
    api_endpoint: 'https://civitai.com/api/v1/models',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Modèles Stable Diffusion + LoRAs + checkpoints communauté.',
  },
  {
    id: 'lmstudio',
    name: 'LM Studio Models',
    category: 'ai-ml',
    url: 'https://lmstudio.ai/models',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Catalogue GGUF curé pour exécution locale.',
  },
  {
    id: 'openai-gpt-store',
    name: 'OpenAI GPT Store',
    category: 'ai-ml',
    url: 'https://chatgpt.com/gpts',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'GPTs custom (read-only, pas d\'API publique de search).',
  },

  /* ----- B. Code / Packages ----- */
  {
    id: 'npm',
    name: 'NPM Registry',
    category: 'code-packages',
    url: 'https://www.npmjs.com',
    api_endpoint: 'https://registry.npmjs.org/-/v1/search',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Packages JavaScript/TypeScript (le plus grand registre du monde).',
  },
  {
    id: 'pypi',
    name: 'PyPI',
    category: 'code-packages',
    url: 'https://pypi.org',
    api_endpoint: 'https://pypi.org/search/',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Packages Python — search HTML (pas d\'API JSON publique).',
  },
  {
    id: 'crates-io',
    name: 'Crates.io',
    category: 'code-packages',
    url: 'https://crates.io',
    api_endpoint: 'https://crates.io/api/v1/crates',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Packages Rust officiels.',
  },
  {
    id: 'maven-central',
    name: 'Maven Central',
    category: 'code-packages',
    url: 'https://search.maven.org',
    api_endpoint: 'https://search.maven.org/solrsearch/select',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Packages Java/Kotlin/Scala JVM.',
  },
  {
    id: 'packagist',
    name: 'Packagist',
    category: 'code-packages',
    url: 'https://packagist.org',
    api_endpoint: 'https://packagist.org/search.json',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Packages PHP Composer.',
  },
  {
    id: 'rubygems',
    name: 'RubyGems',
    category: 'code-packages',
    url: 'https://rubygems.org',
    api_endpoint: 'https://rubygems.org/api/v1/search.json',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Gems Ruby.',
  },
  {
    id: 'pkg-go-dev',
    name: 'pkg.go.dev',
    category: 'code-packages',
    url: 'https://pkg.go.dev',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Modules Go (search HTML).',
  },
  {
    id: 'hex-pm',
    name: 'Hex.pm',
    category: 'code-packages',
    url: 'https://hex.pm',
    api_endpoint: 'https://hex.pm/api/packages',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Packages Elixir / Erlang.',
  },

  /* ----- C. GitHub Ecosystem ----- */
  {
    id: 'github-marketplace',
    name: 'GitHub Marketplace (Actions + Apps)',
    category: 'github',
    url: 'https://github.com/marketplace',
    api_endpoint: 'https://api.github.com/search/repositories',
    api_key_required: true,
    api_key_service: 'ax_github_token',
    search_method: 'api-key',
    free_tier_available: true,
    rate_limit: '5000/h authenticated',
    pwa_compatible: true,
    cors_friendly: true,
    description: 'GitHub Actions, Apps et integrations CI/CD.',
  },
  {
    id: 'github-topics',
    name: 'GitHub Topics Trending',
    category: 'github',
    url: 'https://github.com/topics',
    api_endpoint: 'https://api.github.com/search/repositories',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    rate_limit: '60/h unauthenticated',
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Repos GitHub par topic (trending = stars desc + created last week).',
  },

  /* ----- D. Plugins / Extensions ----- */
  {
    id: 'claude-plugins',
    name: 'Claude.com Plugins (Anthropic)',
    category: 'extensions',
    url: 'https://claude.com/plugins',
    api_key_required: false,
    search_method: 'static-list',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Plugins Claude/MCP (catalog 196 — voir apex-plugins-marketplace.ts).',
  },
  {
    id: 'vscode-marketplace',
    name: 'VS Code Marketplace',
    category: 'extensions',
    url: 'https://marketplace.visualstudio.com/vscode',
    api_endpoint: 'https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Extensions Visual Studio Code (POST query, CORS bloqué).',
  },
  {
    id: 'jetbrains-marketplace',
    name: 'JetBrains Marketplace',
    category: 'extensions',
    url: 'https://plugins.jetbrains.com',
    api_endpoint: 'https://plugins.jetbrains.com/api/searchPlugins',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Plugins IntelliJ / WebStorm / PyCharm / Rider.',
  },
  {
    id: 'chrome-webstore',
    name: 'Chrome Web Store',
    category: 'extensions',
    url: 'https://chromewebstore.google.com',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Extensions Chrome / Edge Chromium.',
  },
  {
    id: 'firefox-addons',
    name: 'Firefox Add-ons',
    category: 'extensions',
    url: 'https://addons.mozilla.org',
    api_endpoint: 'https://addons.mozilla.org/api/v5/addons/search/',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Extensions Firefox AMO.',
  },
  {
    id: 'edge-addons',
    name: 'Microsoft Edge Add-ons',
    category: 'extensions',
    url: 'https://microsoftedge.microsoft.com/addons',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Extensions Edge legacy + Chromium.',
  },

  /* ----- E. Automation / Workflows ----- */
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'automation',
    url: 'https://zapier.com/apps',
    api_endpoint: 'https://zapier.com/api/v3/apps/',
    api_key_required: true,
    api_key_service: 'ax_zapier_token',
    search_method: 'oauth-api',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: '5000+ apps integrations (CRM, mail, DB, no-code workflows).',
  },
  {
    id: 'make',
    name: 'Make.com (Integromat)',
    category: 'automation',
    url: 'https://www.make.com/en/integrations',
    api_key_required: true,
    api_key_service: 'ax_make_token',
    search_method: 'oauth-api',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Workflows visuels avec 1500+ apps connectées.',
  },
  {
    id: 'n8n',
    name: 'n8n Community Workflows',
    category: 'automation',
    url: 'https://n8n.io/workflows',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Workflows open-source self-hostable.',
  },
  {
    id: 'ifttt',
    name: 'IFTTT',
    category: 'automation',
    url: 'https://ifttt.com/explore',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'If This Then That — applets simples cross-services.',
  },
  {
    id: 'power-automate',
    name: 'Microsoft Power Automate',
    category: 'automation',
    url: 'https://powerautomate.microsoft.com/connectors',
    api_key_required: true,
    api_key_service: 'ax_microsoft_token',
    search_method: 'oauth-api',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Workflows Microsoft 365 (Office, Teams, SharePoint).',
  },

  /* ----- F. SaaS / Apps ----- */
  {
    id: 'apple-app-store',
    name: 'Apple App Store',
    category: 'saas',
    url: 'https://www.apple.com/app-store/',
    api_endpoint: 'https://itunes.apple.com/search',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Apps iOS via iTunes Search API (gratuit, CORS OK).',
  },
  {
    id: 'google-play',
    name: 'Google Play Store',
    category: 'saas',
    url: 'https://play.google.com/store',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Apps Android (search HTML, pas d\'API publique).',
  },
  {
    id: 'slack-apps',
    name: 'Slack App Directory',
    category: 'saas',
    url: 'https://slack.com/apps',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Apps et bots Slack.',
  },
  {
    id: 'notion-templates',
    name: 'Notion Templates',
    category: 'saas',
    url: 'https://www.notion.so/templates',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Templates Notion gratuits + payants.',
  },
  {
    id: 'stripe-apps',
    name: 'Stripe Apps',
    category: 'saas',
    url: 'https://marketplace.stripe.com',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Apps Stripe pour étendre paiements.',
  },
  {
    id: 'shopify-apps',
    name: 'Shopify App Store',
    category: 'saas',
    url: 'https://apps.shopify.com',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Apps Shopify (e-commerce).',
  },
  {
    id: 'wordpress-plugins',
    name: 'WordPress.org Plugins',
    category: 'saas',
    url: 'https://wordpress.org/plugins',
    api_endpoint: 'https://api.wordpress.org/plugins/info/1.2/',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Plugins WordPress gratuits.',
  },
  {
    id: 'salesforce-appexchange',
    name: 'Salesforce AppExchange',
    category: 'saas',
    url: 'https://appexchange.salesforce.com',
    api_key_required: true,
    api_key_service: 'ax_salesforce_token',
    search_method: 'oauth-api',
    free_tier_available: false,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Apps Salesforce CRM (B2B).',
  },

  /* ----- G. Cloud / Infrastructure ----- */
  {
    id: 'aws-marketplace',
    name: 'AWS Marketplace',
    category: 'cloud',
    url: 'https://aws.amazon.com/marketplace',
    api_key_required: true,
    api_key_service: 'ax_aws_token',
    search_method: 'api-key',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'AMIs, SaaS, datasets, ML models AWS.',
  },
  {
    id: 'azure-marketplace',
    name: 'Azure Marketplace',
    category: 'cloud',
    url: 'https://azuremarketplace.microsoft.com',
    api_key_required: true,
    api_key_service: 'ax_azure_token',
    search_method: 'api-key',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'VMs, SaaS, dev tools Azure.',
  },
  {
    id: 'gcp-marketplace',
    name: 'Google Cloud Marketplace',
    category: 'cloud',
    url: 'https://console.cloud.google.com/marketplace',
    api_key_required: true,
    api_key_service: 'ax_gcp_token',
    search_method: 'api-key',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Solutions GCP (Compute, BigQuery, AI Platform).',
  },
  {
    id: 'cloudflare-templates',
    name: 'Cloudflare Workers Templates',
    category: 'cloud',
    url: 'https://workers.cloudflare.com/built-with',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Templates Workers + Pages Cloudflare.',
  },
  {
    id: 'vercel-templates',
    name: 'Vercel Templates',
    category: 'cloud',
    url: 'https://vercel.com/templates',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Templates Next.js / Astro / Svelte deploy 1-clic.',
  },
  {
    id: 'netlify-templates',
    name: 'Netlify Templates',
    category: 'cloud',
    url: 'https://www.netlify.com/templates',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Templates Jamstack (Hugo, Eleventy, Gatsby).',
  },
  {
    id: 'railway-templates',
    name: 'Railway Templates',
    category: 'cloud',
    url: 'https://railway.app/templates',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Templates infra (DB, monitoring, queues).',
  },
  {
    id: 'render-templates',
    name: 'Render Templates',
    category: 'cloud',
    url: 'https://render.com/docs/deploy-an-image',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Blueprints Render (API/web/cron/worker).',
  },
  {
    id: 'docker-hub',
    name: 'Docker Hub',
    category: 'cloud',
    url: 'https://hub.docker.com',
    api_endpoint: 'https://hub.docker.com/v2/search/repositories/',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Images Docker officielles + community.',
  },

  /* ----- H. APIs ----- */
  {
    id: 'rapidapi',
    name: 'RapidAPI',
    category: 'apis',
    url: 'https://rapidapi.com/hub',
    api_key_required: true,
    api_key_service: 'ax_rapidapi_key',
    search_method: 'api-key',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Marketplace 40 000+ APIs (search par catégorie).',
  },
  {
    id: 'apilayer',
    name: 'APILayer',
    category: 'apis',
    url: 'https://apilayer.com/marketplace',
    api_key_required: true,
    api_key_service: 'ax_apilayer_key',
    search_method: 'api-key',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'APIs SaaS prêtes (currency, weather, translation, KYC).',
  },
  {
    id: 'postman-api-network',
    name: 'Postman Public APIs Network',
    category: 'apis',
    url: 'https://www.postman.com/explore',
    api_key_required: false,
    search_method: 'web-scrape',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Collections Postman publiques (workspaces, APIs, mocks).',
  },
  {
    id: 'apis-guru',
    name: 'OpenAPI Directory (apis.guru)',
    category: 'apis',
    url: 'https://apis.guru',
    api_endpoint: 'https://api.apis.guru/v2/list.json',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Directory OpenAPI specs (2400+ APIs documentées).',
  },
  {
    id: 'public-apis',
    name: 'public-apis (community list)',
    category: 'apis',
    url: 'https://github.com/public-apis/public-apis',
    api_endpoint: 'https://api.publicapis.org/entries',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Liste collaborative APIs gratuites.',
  },

  /* ----- I. Datasets / Données ----- */
  {
    id: 'kaggle-datasets',
    name: 'Kaggle Datasets',
    category: 'datasets',
    url: 'https://www.kaggle.com/datasets',
    api_key_required: true,
    api_key_service: 'ax_kaggle_token',
    search_method: 'api-key',
    free_tier_available: true,
    pwa_compatible: false,
    cors_friendly: false,
    search_proxy_required: true,
    description: 'Datasets ML communauté Kaggle.',
  },
  {
    id: 'huggingface-datasets',
    name: 'HuggingFace Datasets',
    category: 'datasets',
    url: 'https://huggingface.co/datasets',
    api_endpoint: 'https://huggingface.co/api/datasets',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Datasets HF (NLP, vision, audio).',
  },
  {
    id: 'data-gouv-fr',
    name: 'data.gouv.fr',
    category: 'datasets',
    url: 'https://www.data.gouv.fr',
    api_endpoint: 'https://www.data.gouv.fr/api/1/datasets/',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Open Data France (administration, INSEE, ministères).',
  },
  {
    id: 'data-europa-eu',
    name: 'data.europa.eu',
    category: 'datasets',
    url: 'https://data.europa.eu/data/datasets',
    api_endpoint: 'https://data.europa.eu/api/hub/search/search',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Open Data Union européenne (Eurostat, EEA, EuroVoc).',
  },

  /* ----- J. Anthropic-specific ----- */
  {
    id: 'anthropic-cookbook',
    name: 'Anthropic Cookbook (skills)',
    category: 'anthropic',
    url: 'https://github.com/anthropics/anthropic-cookbook',
    api_endpoint: 'https://api.github.com/repos/anthropics/anthropic-cookbook/contents',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Recettes officielles Claude (skills, prompts, examples).',
  },
  {
    id: 'claude-code-skills',
    name: 'Claude Code Skills',
    category: 'anthropic',
    url: 'https://github.com/anthropics/claude-code',
    api_endpoint: 'https://api.github.com/repos/anthropics/claude-code/contents',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'Skills Claude Code officiels (review, security-review, init…).',
  },
  {
    id: 'mcp-servers',
    name: 'MCP Servers (modelcontextprotocol)',
    category: 'anthropic',
    url: 'https://github.com/modelcontextprotocol/servers',
    api_endpoint: 'https://api.github.com/repos/modelcontextprotocol/servers/contents',
    api_key_required: false,
    search_method: 'public-api',
    free_tier_available: true,
    pwa_compatible: true,
    cors_friendly: true,
    description: 'MCP Servers officiels + community (filesystem, git, brave, …).',
  },
];

